PORT = 5000;

MONGO_URL=YOUR MONGO_URL

JWT_SECRET=Your long JWT_SECRET 
JWT_EXPIRY=<JWT_EXPIRY>

// FILE UPLOAD 
CLOUDINARY_CLOUD_NAME=YOUR CLOUDINARY_CLOUD_NAME
CLOUDINARY_API_KEY=YOUR CLOUDINARY_API_KEY
CLOUDINARY_API_SECRET=YOUR CLOUDINARY_API_SECRET

SMTP_HOST=YOUR SMTP_HOST
SMTP_PORT=YOUR SMTP_PORT
SMTP_USERNAME=YOUR SMTP_USERNAME
SMTP_PASSWORD=YOUR SMTP_PASSWORD
SMTP_FROM_EMAIL=YOUR SMTP_FROM_EMAIL

//PAYMENT GETWAY
RAZORPAY_KEY_ID=YOUR RAZORPAY_KEY_ID
RAZORPAY_SECRET=YOUR RAZORPAY_SECRET
RAZORPAY_PLAN_ID=YOUR RAZORPAY_PLAN_ID

FRONTEND_URL=YOUR FRONTEND_URL

CONTACT_US_EMAIL=YOUR CONTACT_US_EMAIL